import type { WorkflowRun } from "./types.js";

export function renderDashboardHtml(run: WorkflowRun): string {
  const gateRows = run.baseline.gates.map((gate) => `<tr><td>${escapeHtml(gate.gate)}</td><td class="${gate.status.toLowerCase()}">${gate.status}</td><td>${gate.evidenceRefs.length}</td><td>${escapeHtml(gate.reason)}</td></tr>`).join("");
  const redRows = run.redTeam.map((scenario) => `<tr><td>${escapeHtml(scenario.fault)}</td><td class="${scenario.decision.toLowerCase()}">${scenario.decision}</td><td>${escapeHtml(scenario.findings[0]?.observed ?? "")}</td></tr>`).join("");
  const nodes = run.plan.nodes.map((node, index) => `<div class="node"><strong>${index + 1}. ${escapeHtml(node.skill)}</strong><small>${escapeHtml(node.purpose)}</small><span>depends on: ${node.dependsOn.length ? escapeHtml(node.dependsOn.join(", ")) : "none"}</span></div>`).join("");
  const messages = run.tradeCase.messages.map((message) => `<li><code>${escapeHtml(message.type)}</code> ${escapeHtml(message.skill)} · attempt ${message.attempt} · ${escapeHtml(message.status)}</li>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BeeTrust Trade War Room</title><style>body{font-family:system-ui,Segoe UI,sans-serif;background:#f5f7f4;color:#17352a;max-width:1200px;margin:0 auto;padding:32px}h1{margin-bottom:4px}.hero{display:flex;gap:24px;align-items:center;background:#17352a;color:#fff;padding:20px;border-radius:14px}.badge{font-size:28px;font-weight:800;background:#46c979;color:#063b1e;padding:8px 14px;border-radius:10px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px;margin:20px 0}.node{background:#fff;border:1px solid #c9ded2;border-radius:10px;padding:14px;display:flex;flex-direction:column;gap:6px;box-shadow:0 2px 6px #17352a12}.node small{min-height:42px;color:#456}.node span{font-size:12px;color:#678}.panel{background:#fff;border-radius:12px;padding:18px;margin:16px 0;box-shadow:0 2px 6px #17352a12}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:9px;border-bottom:1px solid #deebe3;text-align:left}.pass,.release{color:#08753c;font-weight:700}.review{color:#9b5e00;font-weight:700}.blocked{color:#b42318;font-weight:700}code{background:#eaf4ee;padding:2px 5px;border-radius:4px}</style></head><body><div class="hero"><div><h1>BeeTrust Trade War Room</h1><div>Case ${escapeHtml(run.tradeCase.caseId)} · batch ${escapeHtml(run.tradeCase.batchId)} · ${escapeHtml(run.tradeCase.destination)}</div></div><div class="badge">${run.baseline.decision}</div></div><div class="panel"><h2>Collaborative DAG</h2><div class="grid">${nodes}</div></div><div class="panel"><h2>Release evidence matrix · ${run.baseline.score}/100</h2><table><thead><tr><th>Gate</th><th>Status</th><th>Evidence refs</th><th>Reason</th></tr></thead><tbody>${gateRows}</tbody></table></div><div class="panel"><h2>Adversarial simulation</h2><table><thead><tr><th>Fault</th><th>Decision</th><th>Observed finding</th></tr></thead><tbody>${redRows}</tbody></table></div><div class="panel"><h2>Runtime SkillMessage/v1 timeline</h2><ol>${messages}</ol></div></body></html>`;
}

function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}
